import React, { useState } from 'react';
import { TicketItem } from '../types';
import { Ticket, Plus } from 'lucide-react';
import { EmptyState } from '../components/ui/EmptyState';

interface TicketsPageProps {
  tickets: TicketItem[];
  onOpenCreateModal: () => void;
  onViewTicket: (ticket: TicketItem) => void;
  resolvedCount: number;
}

export const TicketsPage: React.FC<TicketsPageProps> = ({
  tickets,
  onOpenCreateModal,
  onViewTicket,
  resolvedCount,
}) => {
  const [activeTab, setActiveTab] = useState<'Open' | 'In Progress' | 'Resolved'>('Open');

  const openCount = tickets.filter((t) => t.status === 'Open').length;
  const inProgressCount = tickets.filter((t) => t.status === 'In Progress').length;

  const filteredTickets = tickets.filter((t) => {
    if (activeTab === 'Open') return t.status === 'Open';
    if (activeTab === 'In Progress') return t.status === 'In Progress';
    return t.status === 'Resolved';
  });

  return (
    <div className="flex-1 flex flex-col gap-4 overflow-y-auto pr-1">
      <div className="flex items-center justify-between">
        <div className="flex flex-col text-left">
          <div className="flex items-center gap-2">
            <Ticket className="w-5 h-5 text-cyan-400" />
            <h2 className="text-xl font-bold text-white tracking-tight">Maintenance Tickets</h2>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Work orders ranked by automation engine (ML health + internal dependency scoring)
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 bg-slate-900/80 p-1 rounded-xl border border-white/10">
            <button
              onClick={() => setActiveTab('Open')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                activeTab === 'Open' ? 'bg-cyan-500 text-white shadow-neonCyan' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Open ({openCount})
            </button>
            <button
              onClick={() => setActiveTab('In Progress')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                activeTab === 'In Progress' ? 'bg-cyan-500 text-white shadow-neonCyan' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              In Progress ({inProgressCount})
            </button>
            <button
              onClick={() => setActiveTab('Resolved')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
                activeTab === 'Resolved' ? 'bg-cyan-500 text-white shadow-neonCyan' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Resolved ({resolvedCount})
            </button>
          </div>

          <button
            onClick={onOpenCreateModal}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white text-xs font-bold shadow-neonCyan transition-all"
          >
            <Plus className="w-4 h-4" />
            <span>Create Ticket</span>
          </button>
        </div>
      </div>

      <div className="glass-panel rounded-2xl p-5 border border-white/10 flex-1 flex flex-col justify-between">
        {filteredTickets.length === 0 ? (
          <EmptyState
            title="No maintenance tickets"
            description={
              activeTab === 'Resolved'
                ? 'No resolved tickets yet. Tickets are created automatically when ML detects faults.'
                : 'No active tickets. Tickets are generated by the automation engine when faults are detected.'
            }
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs border-collapse">
              <thead>
                <tr className="text-slate-400 border-b border-white/10 font-semibold uppercase tracking-wider">
                  <th className="py-3 px-2">Rank</th>
                  <th className="py-3 px-2">Ticket ID</th>
                  <th className="py-3 px-2">Target Component</th>
                  <th className="py-3 px-2">Priority Level</th>
                  <th className="py-3 px-2">Ticket Status</th>
                  <th className="py-3 px-2">Assigned Specialist</th>
                  <th className="py-3 px-2">Created Time</th>
                  <th className="py-3 px-2 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-slate-200">
                {filteredTickets.map((t) => (
                  <tr key={t.id} className="hover:bg-white/5 transition-colors">
                    <td className="py-3 px-2 font-mono text-slate-300" title={t.maintenanceRationale || undefined}>
                      {t.maintenanceOrder != null ? `#${t.maintenanceOrder}` : '—'}
                    </td>
                    <td className="py-3 px-2 font-mono font-bold text-cyan-400">{t.id}</td>
                    <td className="py-3 px-2 font-semibold text-white">{t.componentName || t.componentId}</td>
                    <td className="py-3 px-2">
                      <span
                        className={`inline-block px-2.5 py-1 rounded-full text-xs font-bold ${
                          t.priority === 'Critical'
                            ? 'bg-red-500/20 text-red-400 border border-red-500/30'
                            : t.priority === 'High'
                            ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
                            : 'bg-blue-500/20 text-blue-400 border border-blue-500/30'
                        }`}
                      >
                        {t.priority}
                      </span>
                    </td>
                    <td className="py-3 px-2 text-slate-300 font-medium">{t.status}</td>
                    <td className="py-3 px-2 text-slate-200 font-semibold">{t.assignedTo}</td>
                    <td className="py-3 px-2 text-slate-400">{t.created}</td>
                    <td className="py-3 px-2 text-right">
                      <button
                        onClick={() => onViewTicket(t)}
                        className="px-3 py-1.5 rounded-lg bg-cyan-500/20 hover:bg-cyan-500/40 text-cyan-400 text-xs font-bold transition-all border border-cyan-400/30"
                      >
                        View Order
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
};
