import type { TopologyNode, TopologyEdge } from '../../types/topologyTypes.js';

export const TOPOLOGY_NODES: TopologyNode[] = [
  // --- CHP Unit 1 (CHP01 / R001) ---
  {
    id: 'C001',
    componentId: 'C001',
    assetId: 'A001',
    componentName: 'Engine — CHP Unit 1',
    componentType: 'Engine',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['EngineCore'],
    subsystem: 'Power Generation',
    category: 'Thermal Prime Mover',
  },
  {
    id: 'C002',
    componentId: 'C002',
    assetId: 'A002',
    componentName: 'Bearing — CHP Unit 1',
    componentType: 'Bearing',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['BearingSystem'],
    subsystem: 'Power Generation',
    category: 'Mechanical Support',
  },
  {
    id: 'C003',
    componentId: 'C003',
    assetId: 'A003',
    componentName: 'Lubrication — CHP Unit 1',
    componentType: 'Lubrication',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['LubricationSystem'],
    subsystem: 'Lubrication',
    category: 'Fluid Handling',
  },
  {
    id: 'C004',
    componentId: 'C004',
    assetId: 'A004',
    componentName: 'Cooling — CHP Unit 1',
    componentType: 'Cooling',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['CoolingSystem'],
    subsystem: 'Heat Recovery & Cooling',
    category: 'Thermal Management',
  },
  {
    id: 'C005',
    componentId: 'C005',
    assetId: 'A005',
    componentName: 'Generator — CHP Unit 1',
    componentType: 'Generator',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['GeneratorSystem'],
    subsystem: 'Electrical Generation',
    category: 'Synchronous Alternator',
  },
  {
    id: 'C006',
    componentId: 'C006',
    assetId: 'A006',
    componentName: 'Fuel — CHP Unit 1',
    componentType: 'Fuel',
    machineId: 'CHP01',
    machineName: 'CHP Unit 1',
    roomId: 'R001',
    cadObjects: ['FuelSystem'],
    subsystem: 'Fuel Infrastructure',
    category: 'Fuel Feed',
  },

  // --- CHP Unit 2 (CHP02 / R001) ---
  {
    id: 'C007',
    componentId: 'C007',
    assetId: 'A007',
    componentName: 'Engine — CHP Unit 2',
    componentType: 'Engine',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['EngineCore1'],
    subsystem: 'Power Generation',
    category: 'Thermal Prime Mover',
  },
  {
    id: 'C008',
    componentId: 'C008',
    assetId: 'A008',
    componentName: 'Bearing — CHP Unit 2',
    componentType: 'Bearing',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['BearingSystem1'],
    subsystem: 'Power Generation',
    category: 'Mechanical Support',
  },
  {
    id: 'C009',
    componentId: 'C009',
    assetId: 'A009',
    componentName: 'Lubrication — CHP Unit 2',
    componentType: 'Lubrication',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['LubricationSystem1'],
    subsystem: 'Lubrication',
    category: 'Fluid Handling',
  },
  {
    id: 'C010',
    componentId: 'C010',
    assetId: 'A010',
    componentName: 'Cooling — CHP Unit 2',
    componentType: 'Cooling',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['CoolingSystem1'],
    subsystem: 'Heat Recovery & Cooling',
    category: 'Thermal Management',
  },
  {
    id: 'C011',
    componentId: 'C011',
    assetId: 'A011',
    componentName: 'Generator — CHP Unit 2',
    componentType: 'Generator',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['GeneratorSystem1'],
    subsystem: 'Electrical Generation',
    category: 'Synchronous Alternator',
  },
  {
    id: 'C012',
    componentId: 'C012',
    assetId: 'A012',
    componentName: 'Fuel — CHP Unit 2',
    componentType: 'Fuel',
    machineId: 'CHP02',
    machineName: 'CHP Unit 2',
    roomId: 'R001',
    cadObjects: ['FuelSystem1'],
    subsystem: 'Fuel Infrastructure',
    category: 'Fuel Feed',
  },

  // --- CHP Unit 3 (CHP03 / R001) ---
  {
    id: 'C013',
    componentId: 'C013',
    assetId: 'A013',
    componentName: 'Engine — CHP Unit 3',
    componentType: 'Engine',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['EngineCore2'],
    subsystem: 'Power Generation',
    category: 'Thermal Prime Mover',
  },
  {
    id: 'C014',
    componentId: 'C014',
    assetId: 'A014',
    componentName: 'Bearing — CHP Unit 3',
    componentType: 'Bearing',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['BearingSystem2'],
    subsystem: 'Power Generation',
    category: 'Mechanical Support',
  },
  {
    id: 'C015',
    componentId: 'C015',
    assetId: 'A015',
    componentName: 'Lubrication — CHP Unit 3',
    componentType: 'Lubrication',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['LubricationSystem2'],
    subsystem: 'Lubrication',
    category: 'Fluid Handling',
  },
  {
    id: 'C016',
    componentId: 'C016',
    assetId: 'A016',
    componentName: 'Cooling — CHP Unit 3',
    componentType: 'Cooling',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['CoolingSystem2'],
    subsystem: 'Heat Recovery & Cooling',
    category: 'Thermal Management',
  },
  {
    id: 'C017',
    componentId: 'C017',
    assetId: 'A017',
    componentName: 'Generator — CHP Unit 3',
    componentType: 'Generator',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['GeneratorSystem2'],
    subsystem: 'Electrical Generation',
    category: 'Synchronous Alternator',
  },
  {
    id: 'C018',
    componentId: 'C018',
    assetId: 'A018',
    componentName: 'Fuel — CHP Unit 3',
    componentType: 'Fuel',
    machineId: 'CHP03',
    machineName: 'CHP Unit 3',
    roomId: 'R001',
    cadObjects: ['FuelSystem2'],
    subsystem: 'Fuel Infrastructure',
    category: 'Fuel Feed',
  },

  // --- Utility Pump Station 1 (PUMP01 / R002) ---
  {
    id: 'C019',
    componentId: 'C019',
    assetId: 'A019',
    componentName: 'Pump — Utility Pump Station 1',
    componentType: 'Pump',
    machineId: 'PUMP01',
    machineName: 'Utility Pump Station 1',
    roomId: 'R002',
    cadObjects: ['WaterPump'],
    subsystem: 'Raw Water Intake',
    category: 'Centrifugal Pumping Unit',
  },
  {
    id: 'C020',
    componentId: 'C020',
    assetId: 'A020',
    componentName: 'Motor — Utility Pump Station 1',
    componentType: 'Motor',
    machineId: 'PUMP01',
    machineName: 'Utility Pump Station 1',
    roomId: 'R002',
    cadObjects: ['ElectricMotor'],
    subsystem: 'Raw Water Intake',
    category: 'Electric Drive Motor',
  },
  {
    id: 'C021',
    componentId: 'C021',
    assetId: 'A021',
    componentName: 'Bearing — Utility Pump Station 1',
    componentType: 'Bearing',
    machineId: 'PUMP01',
    machineName: 'Utility Pump Station 1',
    roomId: 'R002',
    cadObjects: ['FlexibleCoupling'],
    subsystem: 'Raw Water Intake',
    category: 'Mechanical Transmission',
  },

  // --- Reverse Osmosis Plant (RO01 / R003) ---
  {
    id: 'C022',
    componentId: 'C022',
    assetId: 'A022',
    componentName: 'Pump — Reverse Osmosis Plant',
    componentType: 'Pump',
    machineId: 'RO01',
    machineName: 'Reverse Osmosis Plant',
    roomId: 'R003',
    cadObjects: ['HighPressureFeedPump'],
    subsystem: 'Reverse Osmosis Filtration',
    category: 'High-Pressure Booster',
  },
  {
    id: 'C023',
    componentId: 'C023',
    assetId: 'A023',
    componentName: 'Membrane — Reverse Osmosis Plant',
    componentType: 'Membrane',
    machineId: 'RO01',
    machineName: 'Reverse Osmosis Plant',
    roomId: 'R003',
    cadObjects: ['ROMembraneBank'],
    subsystem: 'Reverse Osmosis Filtration',
    category: 'Desalination & Purification',
  },
  {
    id: 'C024',
    componentId: 'C024',
    assetId: 'A024',
    componentName: 'Filter — Reverse Osmosis Plant',
    componentType: 'Filter',
    machineId: 'RO01',
    machineName: 'Reverse Osmosis Plant',
    roomId: 'R003',
    cadObjects: ['PreFilterBank'],
    subsystem: 'Raw Water Intake',
    category: 'Particulate Filtration',
  },
  {
    id: 'C025',
    componentId: 'C025',
    assetId: 'A025',
    componentName: 'Valve — Reverse Osmosis Plant',
    componentType: 'Valve',
    machineId: 'RO01',
    machineName: 'Reverse Osmosis Plant',
    roomId: 'R003',
    cadObjects: ['FeedSuctionPiping'],
    subsystem: 'Piping & Distribution',
    category: 'Process Piping',
  },

  // --- Wastewater Treatment Plant (WW01 / R004) ---
  {
    id: 'C026',
    componentId: 'C026',
    assetId: 'A026',
    componentName: 'Pump — Wastewater Treatment Plant',
    componentType: 'Pump',
    machineId: 'WW01',
    machineName: 'Wastewater Treatment Plant',
    roomId: 'R004',
    cadObjects: ['ProcessDischargeLoop'],
    subsystem: 'Wastewater Treatment',
    category: 'Effluent Handling',
  },
  {
    id: 'C027',
    componentId: 'C027',
    assetId: 'A027',
    componentName: 'Filter — Wastewater Treatment Plant',
    componentType: 'Filter',
    machineId: 'WW01',
    machineName: 'Wastewater Treatment Plant',
    roomId: 'R004',
    cadObjects: ['RejectConcentrateLoop'],
    subsystem: 'Wastewater Treatment',
    category: 'Brine Management',
  },
  {
    id: 'C028',
    componentId: 'C028',
    assetId: 'A028',
    componentName: 'Valve — Wastewater Treatment Plant',
    componentType: 'Valve',
    machineId: 'WW01',
    machineName: 'Wastewater Treatment Plant',
    roomId: 'R004',
    cadObjects: ['InstrumentationDrainNetwork'],
    subsystem: 'Collection & Drainage',
    category: 'Drainage Network',
  },

  // --- Satellite & Data Drives (DISH01 / R005) ---
  {
    id: 'C029',
    componentId: 'C029',
    assetId: 'A029',
    componentName: 'Azimuth Drive — Satellite Antenna',
    componentType: 'Drive',
    machineId: 'DISH01',
    machineName: 'Satellite Ground Station',
    roomId: 'R005',
    cadObjects: ['AzimuthDrive'],
    subsystem: 'Satellite Communications',
    category: 'Precision Drive Mechanism',
  },
  {
    id: 'C030',
    componentId: 'C030',
    assetId: 'A030',
    componentName: 'Elevation Drive — Satellite Antenna',
    componentType: 'Drive',
    machineId: 'DISH01',
    machineName: 'Satellite Ground Station',
    roomId: 'R005',
    cadObjects: ['ElevationDrive'],
    subsystem: 'Satellite Communications',
    category: 'Precision Drive Mechanism',
  },
  {
    id: 'C031',
    componentId: 'C031',
    assetId: 'A031',
    componentName: 'Gearbox — Satellite Antenna',
    componentType: 'Gearbox',
    machineId: 'DISH01',
    machineName: 'Satellite Ground Station',
    roomId: 'R005',
    cadObjects: ['Gearbox'],
    subsystem: 'Satellite Communications',
    category: 'Mechanical Transmission',
  },
  {
    id: 'C032',
    componentId: 'C032',
    assetId: 'A032',
    componentName: 'Drive Motor — Satellite Antenna',
    componentType: 'Motor',
    machineId: 'DISH01',
    machineName: 'Satellite Ground Station',
    roomId: 'R005',
    cadObjects: ['DriveMotor'],
    subsystem: 'Satellite Communications',
    category: 'Brushless Servo Motor',
  },

  // --- Data & Telecom Centre (SERVER01 / R006) ---
  {
    id: 'C034',
    componentId: 'C034',
    assetId: 'A034',
    componentName: 'Storage — Server Room Rack',
    componentType: 'Storage',
    machineId: 'SERVER01',
    machineName: 'Server Room Rack',
    roomId: 'R006',
    cadObjects: ['Data+Center.obj (1)'],
    subsystem: 'Data Centre Infrastructure',
    category: 'Computing Infrastructure',
  },
  {
    id: 'C035',
    componentId: 'C035',
    assetId: 'A035',
    componentName: 'Power Supply — Server Room Rack',
    componentType: 'Power Supply',
    machineId: 'SERVER01',
    machineName: 'Server Room Rack',
    roomId: 'R006',
    cadObjects: ['ControlCabinet'],
    subsystem: 'Electrical & Control',
    category: 'Power & Logic Distribution',
  },
];

export const TOPOLOGY_EDGES: TopologyEdge[] = [
  // --- CHP Unit 1 Physical Relationships ---
  { source: 'C001', target: 'C005', relationship: 'DRIVES', description: 'Unit 1 Engine Core turns Alternator shaft' },
  { source: 'C003', target: 'C001', relationship: 'LUBRICATES', description: 'Lube oil module pressurizes Unit 1 bearings and engine core' },
  { source: 'C004', target: 'C001', relationship: 'COOLS', description: 'Cooling jacket loop regulates Unit 1 thermal load' },
  { source: 'C006', target: 'C001', relationship: 'FEEDS', description: 'Fuel injection circuit supplies polar diesel to Unit 1 engine' },
  { source: 'C002', target: 'C001', relationship: 'PART_OF', description: 'Main bearing system supports Unit 1 crankshaft' },
  { source: 'C005', target: 'C001', relationship: 'DEPENDS_ON', description: 'Generator load depends on Engine Core prime mover' },
  { source: 'C001', target: 'C004', relationship: 'DEPENDS_ON', description: 'Engine Core thermal stability depends on Cooling System' },
  { source: 'C001', target: 'C003', relationship: 'DEPENDS_ON', description: 'Engine Core mechanical life depends on Lubrication' },
  { source: 'C001', target: 'C006', relationship: 'DEPENDS_ON', description: 'Engine Core operation depends on Fuel delivery' },

  // --- CHP Unit 2 Physical Relationships ---
  { source: 'C007', target: 'C011', relationship: 'DRIVES', description: 'Unit 2 Engine Core turns Alternator shaft' },
  { source: 'C009', target: 'C007', relationship: 'LUBRICATES', description: 'Lube oil module pressurizes Unit 2 bearings and engine core' },
  { source: 'C010', target: 'C007', relationship: 'COOLS', description: 'Cooling jacket loop regulates Unit 2 thermal load' },
  { source: 'C012', target: 'C007', relationship: 'FEEDS', description: 'Fuel injection circuit supplies polar diesel to Unit 2 engine' },
  { source: 'C008', target: 'C007', relationship: 'PART_OF', description: 'Main bearing system supports Unit 2 crankshaft' },
  { source: 'C011', target: 'C007', relationship: 'DEPENDS_ON', description: 'Generator load depends on Engine Core prime mover' },
  { source: 'C007', target: 'C010', relationship: 'DEPENDS_ON', description: 'Engine Core thermal stability depends on Cooling System' },
  { source: 'C007', target: 'C009', relationship: 'DEPENDS_ON', description: 'Engine Core mechanical life depends on Lubrication' },
  { source: 'C007', target: 'C012', relationship: 'DEPENDS_ON', description: 'Engine Core operation depends on Fuel delivery' },

  // --- CHP Unit 3 Physical Relationships ---
  { source: 'C013', target: 'C017', relationship: 'DRIVES', description: 'Unit 3 Engine Core turns Alternator shaft' },
  { source: 'C015', target: 'C013', relationship: 'LUBRICATES', description: 'Lube oil module pressurizes Unit 3 bearings and engine core' },
  { source: 'C016', target: 'C013', relationship: 'COOLS', description: 'Cooling jacket loop regulates Unit 3 thermal load' },
  { source: 'C018', target: 'C013', relationship: 'FEEDS', description: 'Fuel injection circuit supplies polar diesel to Unit 3 engine' },
  { source: 'C014', target: 'C013', relationship: 'PART_OF', description: 'Main bearing system supports Unit 3 crankshaft' },
  { source: 'C017', target: 'C013', relationship: 'DEPENDS_ON', description: 'Generator load depends on Engine Core prime mover' },
  { source: 'C013', target: 'C016', relationship: 'DEPENDS_ON', description: 'Engine Core thermal stability depends on Cooling System' },
  { source: 'C013', target: 'C015', relationship: 'DEPENDS_ON', description: 'Engine Core mechanical life depends on Lubrication' },
  { source: 'C013', target: 'C018', relationship: 'DEPENDS_ON', description: 'Engine Core operation depends on Fuel delivery' },

  // --- Utility Pump Station 1 (PUMP01) Relationships ---
  { source: 'C020', target: 'C019', relationship: 'DRIVES', description: 'Drive Motor rotates intake Water Pump' },
  { source: 'C021', target: 'C020', relationship: 'CONNECTS_TO', description: 'Flexible Coupling connects Motor shaft to Pump' },
  { source: 'C019', target: 'C020', relationship: 'DEPENDS_ON', description: 'Water Pump operation depends on Drive Motor' },

  // --- Reverse Osmosis Plant (RO01) Relationships ---
  { source: 'C025', target: 'C024', relationship: 'CONNECTS_TO', description: 'Feed Suction Valve routes raw water into Pre-Filter' },
  { source: 'C024', target: 'C022', relationship: 'FEEDS', description: 'Pre-Filter Bank delivers strained feed to High Pressure Pump' },
  { source: 'C022', target: 'C023', relationship: 'SUPPLIES', description: 'High Pressure Feed Pump elevates feed water to RO Membranes' },
  { source: 'C023', target: 'C022', relationship: 'DEPENDS_ON', description: 'RO Membrane separation depends on High Pressure Feed Pump' },
  { source: 'C022', target: 'C024', relationship: 'DEPENDS_ON', description: 'High Pressure Feed Pump depends on Pre-Filter sediment removal' },

  // --- Wastewater Treatment Plant (WW01) Relationships ---
  { source: 'C028', target: 'C026', relationship: 'CONNECTS_TO', description: 'Drain Valve Network routes wastewater into Discharge Pump' },
  { source: 'C026', target: 'C027', relationship: 'FEEDS', description: 'Discharge Pump forces effluent into Reject Concentrate Filter' },
  { source: 'C027', target: 'C026', relationship: 'DEPENDS_ON', description: 'Reject Filter depends on Discharge Pump pressure' },

  // --- Satellite Antenna Drives (DISH01) Relationships ---
  { source: 'C032', target: 'C031', relationship: 'DRIVES', description: 'Drive Motor turns Planetary Gearbox' },
  { source: 'C031', target: 'C029', relationship: 'DRIVES', description: 'Planetary Gearbox rotates Azimuth Drive turntable' },
  { source: 'C031', target: 'C030', relationship: 'DRIVES', description: 'Planetary Gearbox drives Elevation tilt actuator' },
  { source: 'C029', target: 'C031', relationship: 'DEPENDS_ON', description: 'Azimuth Drive depends on Planetary Gearbox' },
  { source: 'C030', target: 'C031', relationship: 'DEPENDS_ON', description: 'Elevation Drive depends on Planetary Gearbox' },

  // --- Data & Telecom Centre (SERVER01) Relationships ---
  { source: 'C035', target: 'C034', relationship: 'SUPPLIES', description: 'Power Supply Control Cabinet feeds server rack storage power' },
  { source: 'C034', target: 'C035', relationship: 'DEPENDS_ON', description: 'Server Storage depends on Power Supply unit' },
];
